baseurl = "https://paranoi-i.github.io/"
title = "paranoii"
theme = "hugo-theme-console"
languageCode = "en-us"
enableRobotsTXT = true
canonifyURLs = true

[params]
  # Cutting off the page title to two chars for mobile (console-demo -> co)
  titleCutting = false
  
  Description = "Noticing UFO and alien-related patterns that no one else has"

  # Set the animation style -- https://animate.style/
  # To disable animations, please remove or comment animationStyle parameter
  animateStyle = "animated zoomIn fast" 

  #[[params.navlinks]]
  #name = "about/"
  #url = "about/"

  [[params.navlinks]]
  name = "⦑ cast your ego aside ⦒"
  url = "egoless/"
  
  #[[params.navlinks]]
  #name = "photos/"
  #url = "photos/"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[caches]
  [caches.images]
    dir = ':cacheDir/images'

